---
- name: Deploy host 
  tags: ["deploy"]
  vars: 
    CD_DIR: "{{ CONFIG_DIR }}/compose"
  block: 
  - name: Clone IAC
    ansible.builtin.git:
      repo: https://github.com/meyersa/iac-cd.git
      dest: "{{ CD_DIR }}"
      version: main
    
  # Git pull 
  # save output to see if there is change 

  - name: Find env templates
    find:
      paths: "{{ CD_DIR }}"
      patterns: "*.j2"
      recurse: yes
      hidden: true
    register: j2_files

  - name: Render env files
    template:
      src: "{{ item.path }}"
      dest: "{{ item.path | regex_replace('\\.j2$', '') }}"
    loop: "{{ j2_files.files }}"

  # Apply 

  # Run Checkout 

  # Roll back on rescue