# Only restart ddclient on change
- name: restart ddclient pub
  ansible.builtin.systemd:
    name: ddclient-pub
    state: restarted
    enabled: true

- name: restart ddclient warp
  ansible.builtin.systemd:
    name: ddclient-warp
    state: restarted
    enabled: true

- name: restart docker
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    enabled: true

- name: reload sshd
  ansible.builtin.systemd:
    name: ssh.service
    state: reloaded
