---
- name: Post webhook
  ansible.builtin.uri:
    url: "https://discord.com/api/webhooks/{{ lookup('bitwarden.secrets.lookup', webhook_id_secret) }}/{{ lookup('bitwarden.secrets.lookup', webhook_token_secret) }}"
    method: POST
    body_format: json
    status_code: 204
    body:
      username: "{{ webhook_username }}"
      avatar_url: "{{ webhook_avatar_url }}"
      embeds:
        - title: "{{ webhook_title | default(webhook_default_title) }}"
          description: "{{ webhook_description | default('') }}"
          color: "{{ webhook_color | default(webhook_default_color) }}"
          fields: "{{ webhook_fields | default([]) }}"
  vars:
    webhook_status_effective: "{{ webhook_status | default('success') }}"
    webhook_id_secret: "{{ ERROR_WEBHOOK_ID if webhook_status_effective == 'failed' else INFO_WEBHOOK_ID }}"
    webhook_token_secret: "{{ ERROR_WEBHOOK_TOKEN if webhook_status_effective == 'failed' else INFO_WEBHOOK_TOKEN }}"
    webhook_default_color: "{{ 15158332 if webhook_status_effective == 'failed' else 3447003 }}"
    webhook_default_title: "{{ 'Ansible error' if webhook_status_effective == 'failed' else 'Ansible info' }}"
  delegate_to: localhost
  become: false
  no_log: true
  failed_when: false
