---
- name: Clean OS 
  tags: ["clean-os"]
  block: 
    - name: Run JournalCTL Vacuum
      ansible.builtin.command: journalctl --vacuum-size 10M

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
        purge: true
        lock_timeout: 360
      retries: 3 

    - name: Remove packages from local cache 
      ansible.builtin.apt:
        autoclean: yes
        lock_timeout: 360
      retries: 3 
