---
- name: Clean Docker 
  tags: ["clean-docker"]
  block: 
    - name: Check if Docker is installed
      ansible.builtin.command: "docker --version"
      register: DOCKER_CHECK
      ignore_errors: yes

    - name: Run Docker System Prune
      when: DOCKER_CHECK.rc == 0
      ansible.builtin.command: docker system prune -f