---
- name: Configure admin account and SSH Access
  tags: ["access"]
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ BW_LOGIN_USER }}/.ssh"
        state: directory
        owner: "{{ BW_LOGIN_USER }}"
        group: "{{ BW_LOGIN_USER }}"
        mode: "0700"

    - name: Fetch public keys from GitHub
      ansible.builtin.uri:
        url: "https://api.github.com/users/meyersa/keys"
        return_content: yes
        headers: 
          Authorization: "Bearer {{ lookup('bitwarden.secrets.lookup', GITHUB_BEARER) }}"

      register: GITHUB_KEYS

    - name: Ensure authorized_keys file exists
      ansible.builtin.file:
        path: "/home/{{ BW_LOGIN_USER }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ BW_LOGIN_USER }}"
        group: "{{ BW_LOGIN_USER }}"
        mode: "0600"

    - name: Add GitHub public keys to authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ BW_LOGIN_USER }}/.ssh/authorized_keys"
        line: "{{ item.key }}"
        create: yes
        owner: "{{ BW_LOGIN_USER }}"
        group: "{{ BW_LOGIN_USER }}"
        mode: "0600"
        state: present
      loop: "{{ GITHUB_KEYS.json }}"

    - name: Ensure sudoers file for admin user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ BW_LOGIN_USER }}"
        content: "{{ BW_LOGIN_USER }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: Ensure sudoers file for remote user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}"
        content: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: Sync remote user authorized keys
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/meyersa/ansible/main/ansible.pub"
        dest: "/home/{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}/.ssh/authorized_keys"
        owner: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}"
        group: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}"
        mode: "0600"
        headers: 
          Authorization: "Bearer {{ lookup('bitwarden.secrets.lookup', GITHUB_BEARER) }}"


    - name: Disable passwordless SSH authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+yes'
        line: "PasswordAuthentication no"
        state: present
      notify: reload sshd
