---
- name: Configure admin account and SSH Access
  tags: ["access"]
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ bw_LOGIN_USER }}/.ssh"
        state: directory
        owner: "{{ bw_LOGIN_USER }}"
        group: "{{ bw_LOGIN_USER }}"
        mode: "0700"

    - name: Fetch public keys from GitHub
      ansible.builtin.uri:
        url: "https://api.github.com/users/meyersa/keys"
        return_content: yes
      register: github_keys

    - name: Ensure authorized_keys file exists
      ansible.builtin.file:
        path: "/home/{{ bw_LOGIN_USER }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ bw_LOGIN_USER }}"
        group: "{{ bw_LOGIN_USER }}"
        mode: "0600"

    - name: Add GitHub public keys to authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ bw_LOGIN_USER }}/.ssh/authorized_keys"
        line: "{{ item.key }}"
        create: yes
        owner: "{{ bw_LOGIN_USER }}"
        group: "{{ bw_LOGIN_USER }}"
        mode: "0600"
        state: present
      loop: "{{ github_keys.json }}"

    - name: Ensure sudoers file for admin user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ bw_LOGIN_USER }}"
        content: "{{ bw_LOGIN_USER }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: Ensure sudoers file for ansible user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: Sync Ansible_user authorized keys
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/meyersa/ansible/main/ansible.pub"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Disable passwordless SSH authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+yes'
        line: "PasswordAuthentication no"
        state: present
      notify: reload sshd
