---
- name: Set Hostname
  tags: ["hostname"]
  block:
  - name: Set a hostname specifying strategy
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      use: systemd

  - name: Manage localhost hosts entry
    blockinfile:
      path: /etc/hosts
      marker: "# {mark} ANSIBLE LOCALHOST"
      block: |
        127.0.0.1 localhost {{ inventory_hostname }}